name: swap CI

on:
  push:
    branches: [ feature/swap ]
  pull_request:
    branches: [ feature/swap ]

jobs:
   build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make crdt-test
      run: ./runtest-crdt --swap --debug-evict-keys -1
