name: mem CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make crdt-test
      run: make crdt-test
